import {Toaster} from '@/components/ui/sonner'
import NavPage from './@nav/page'
import './globals.css'
import localFont from 'next/font/local'
import FooterPage from './@footer/page'
import StrengthPage from './@strength/page'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const svnGraphik = localFont({
  src: [
    {
      path: './font/SVN-Graphik-Regular.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './font/SVN-GraphikMedium.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './font/SVN-Graphik-Semibold.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './font/SVN-Graphik-Bold.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './font/SVN-Graphik-Super.otf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './font/SVN-Graphik-Black.otf',
      weight: '900',
      style: 'normal',
    },
  ],
  variable: '--font-svn-graphik',
  display: 'swap',
})

export default function RootLayout({children}) {
  return (
    <html
      lang='en'
      suppressHydrationWarning={true}
    >
      <head>
        {/* <link rel="canonical" href="https://abc.com" />
        <meta
          name="google-site-verification"
          content="xZu-R_qHMGQVpE1mZc1JuwL4Zj3Hi9ZybbsJfxgzQiQ"
        />
        <meta name="DC.title" content="Vietnam Cheers Hostel Official Site" />
        <meta name="geo.region" content="VN-HN" />
        <meta name="geo.placename" content="H&agrave; Nội" />
        <meta
          name="geo.position"
          content="21.028530680620868;105.84580487600834"
        />
        <meta name="ICBM" content="21.028530680620868, 105.84580487600834" /> */}
      </head>
      <body className={svnGraphik.className}>
        <NavPage />
        {children}
        <FooterPage />
        <Toaster />
      </body>
    </html>
  )
}
